channels:
  - conda-forge
  - ncar
dependencies:
  - python=3
  - geocat-comp
  - geocat-datafiles
  - geocat-viz
  - pip
  - pip:
    - sphinx
    - sphinx_rtd_theme
    - netcdf4
    - cartopy
    - matplotlib
    - sphinx-gallery
    - cmaps
    - mock
    - pillow
