channels:
  - conda-forge
  - ncar
dependencies:
  - python=3
  - geocat-comp
  - geocat-datafiles
  - geocat-viz
  - netcdf4
  - cartopy
  - sphinx
  - sphinx_rtd_theme
  - matplotlib
  - sphinx-gallery
  - cmaps
  - mock
  - pillow
